FROM node:22-alpine

WORKDIR /app

# Instala deps primeiro (melhor cache)
COPY package*.json ./
RUN npm ci --omit=dev

# Copia o resto
COPY . .

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "src/server.js"]